# Generated by Django 5.2.7 on 2025-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
