# Generated by Django 5.2.7 on 2025-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loan',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
